@startuml

!theme mytheme

skinparam dpi 200

package "base" {

  class TBModel{
    'Attributes
    # int nOrb
    # int nDim
    # vector<Hop> hop
    # vector<OnSite> onSite
    'Methods
    + void setHop()
    + void setOnSite()
    + Hop getHop()
    + OnSite getOnSite()
  }

  class Hop{
    -complex<double> hop
    -int nOrb1
    -int nOrb2
    -int * n
    -int nDim
    + setHop()
  }

  class OnSite{
    -complex<double> en
    -int nOrb
    + setEn()
  }

  class OData{
  }

  abstract class Hamiltonian{
  +virtual cx_mat H(double * k = NULL) = 0
  +virtual sp_cx_mat spH(double * k = NULL) = 0
  - bool isSparse
}

class Wilson #yellow{
  + Wilson(Hamiltonian)
  + void setLoopDir()
  + cx_mat wilsonLoop()
  + double berryPhase()
  + cx_mat wilsonLoopSupercell()
  + double berryPhaseSupercell()
}

class DOS #yellow{
}

class MultipoleOp #yellow{
}

class LocalizationStats #yellow{
}

class TBCleanH{
  + TBCleanH(TBModel)
  + void setSparse()
}

class BoundaryWilsonH #yellow{
  + BoundaryWilsonH(Hamiltonian, int dir)
}

class BoundarySupercellWilsonH #yellow{
  + BoundarySupercellWilsonH(Hamiltonian, int dir)
}

class TBDisorderedH #yellow{
  + TBDisorderedH(TBModel)
  + void setSparse()
}

class BoundaryGreenH #yellow{
  + BoundaryGreenH(Hamiltonian, int dir)
}

Wilson o-- Hamiltonian
DOS o-- Hamiltonian
MultipoleOp o-- Hamiltonian
LocalizationStats o--Hamiltonian

Hamiltonian <|-- TBCleanH
Hamiltonian <|-- TBDisorderedH
Hamiltonian <|-- BoundaryWilsonH
Hamiltonian <|-- BoundarySupercellWilsonH
Hamiltonian <|-- BoundaryGreenH

TBCleanH o-- TBModel
TBDisorderedH o-- TBModel

TBModel o-- OnSite
TBModel o-- Hop

legend center
    | Color | Type |
    |<#$BOXBG>| Done |
    |<#yellow>| TODO |
endlegend
}

@enduml
